name: Build and Deploy

on:
  push:
    branches: [wkldle]
  pull_request:
    branches: [wkldle]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy
        if: github.ref == 'refs/heads/wkldle'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          branch: compiled
          folder: dist
