name: "daily"
# Run this action whenever an issue is opened
on:
  schedule:
    # Run at 23:59 of every day
    - cron: "59 23 * * *"

jobs:
  play:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: compiled

      - name: Run script
        uses: actions/github-script@v2.0.0
        with:
          script: |
            const path = require('path')
            const scriptPath = path.resolve('./bundle.js')
            const wkldle = require(scriptPath)
            console.log(scriptPath, wkldle)
            console.log(await wkldle.dailyInit(github, context, core))
