name: "daily"
# Run this action whenever an issue is opened
on:
  schedule:
    # Run at 23:59 of every day
    - cron: "59 23 * * *"
jobs:
  play:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Daily init
        run: python daily.py

      - name: Commit and push
        run: |
          git diff
          git add .
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Daily init" -a
          git push
