name: "play"
# Run this action whenever an issue is opened
on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write

jobs:
  play:
    runs-on: ubuntu-latest

    # Only do anything if the issue title start with 'wkldle-'
    if: startsWith(github.event.issue.title, 'wkldle-')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Update game
        run: python wkldle.py
        env:
          TITLE: ${{ github.event.issue.title }}
          USER: ${{ github.event.issue.user.login }}

      - name: Commit and push
        run: |
          git diff
          git add .
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Updated game" -a
          git push
