name: "play"
# Run this action whenever an issue is opened
on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write

jobs:
  play:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: compiled

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_CREATOR: ${{ github.event.issue.user.login }}
        run: ./bundle.js
